# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eg < Formula
  desc "A per-shell environment profile switcher with batteries"
  homepage "https://github.com/stjbrown/env-garden"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stjbrown/env-garden/releases/download/v0.1.0/env-garden_0.1.0_darwin_amd64.tar.gz"
      sha256 "20486900c3de6f7dc7117fd10b4bb7c6bede7b8c1ab43fa4a26c4781650e8530"

      define_method(:install) do
        bin.install "eg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stjbrown/env-garden/releases/download/v0.1.0/env-garden_0.1.0_darwin_arm64.tar.gz"
      sha256 "82cc36764b565137fa798a62c5f9706d86dd730be563d4df6e5941be33f841ae"

      define_method(:install) do
        bin.install "eg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stjbrown/env-garden/releases/download/v0.1.0/env-garden_0.1.0_linux_amd64.tar.gz"
      sha256 "e9fd898ed5f354ba0908d4409e2024bc869a6991c4ac5001355ce16fdf919bcf"
      define_method(:install) do
        bin.install "eg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stjbrown/env-garden/releases/download/v0.1.0/env-garden_0.1.0_linux_arm64.tar.gz"
      sha256 "82a8867567ec80271f99281131e925168a2752b7fd9368b9c805b791d9610ea5"
      define_method(:install) do
        bin.install "eg"
      end
    end
  end

  def caveats
    <<~EOS
      Add the shell integration to your rc file:
        echo 'eval "$(eg init zsh)"'  >> ~/.zshrc
        echo 'eval "$(eg init bash)"' >> ~/.bashrc
    EOS
  end

  test do
    system "#{bin}/eg", "--version"
  end
end
