# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eg < Formula
  desc "A per-shell environment profile switcher with batteries"
  homepage "https://github.com/stjbrown/env-garden"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stjbrown/env-garden/releases/download/v0.2.0/env-garden_0.2.0_darwin_amd64.tar.gz"
      sha256 "543d4a2bb85250abd6d99e0e46fb6a3cf559d05fcb3db4f2e3213cd97143610b"

      define_method(:install) do
        bin.install "eg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stjbrown/env-garden/releases/download/v0.2.0/env-garden_0.2.0_darwin_arm64.tar.gz"
      sha256 "1f8f09d679e741aba8a58118bd30448d46dd5225970ae110de75c0861f147c64"

      define_method(:install) do
        bin.install "eg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stjbrown/env-garden/releases/download/v0.2.0/env-garden_0.2.0_linux_amd64.tar.gz"
      sha256 "26f9d8a3e2965292da9bcb48bf5c301f457ac49ca0268e688297c8d7fc946337"
      define_method(:install) do
        bin.install "eg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stjbrown/env-garden/releases/download/v0.2.0/env-garden_0.2.0_linux_arm64.tar.gz"
      sha256 "b2dc01b4e59a964aeb44851ceb6475de343d3e7bfef20cfbd77ffc36e826f558"
      define_method(:install) do
        bin.install "eg"
      end
    end
  end

  def caveats
    <<~EOS
      Add the shell integration to your rc file:
        echo 'eval "$(eg init zsh)"'  >> ~/.zshrc
        echo 'eval "$(eg init bash)"' >> ~/.bashrc
    EOS
  end

  test do
    system "#{bin}/eg", "--version"
  end
end
